/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomePageRouteImport } from './routes/WelcomePage'
import { Route as LoginPageRouteImport } from './routes/LoginPage'

const WelcomePageRoute = WelcomePageRouteImport.update({
  id: '/WelcomePage',
  path: '/WelcomePage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/LoginPage',
  path: '/LoginPage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/LoginPage': typeof LoginPageRoute
  '/WelcomePage': typeof WelcomePageRoute
}
export interface FileRoutesByTo {
  '/LoginPage': typeof LoginPageRoute
  '/WelcomePage': typeof WelcomePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/LoginPage': typeof LoginPageRoute
  '/WelcomePage': typeof WelcomePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/LoginPage' | '/WelcomePage'
  fileRoutesByTo: FileRoutesByTo
  to: '/LoginPage' | '/WelcomePage'
  id: '__root__' | '/LoginPage' | '/WelcomePage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginPageRoute: typeof LoginPageRoute
  WelcomePageRoute: typeof WelcomePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/WelcomePage': {
      id: '/WelcomePage'
      path: '/WelcomePage'
      fullPath: '/WelcomePage'
      preLoaderRoute: typeof WelcomePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LoginPage': {
      id: '/LoginPage'
      path: '/LoginPage'
      fullPath: '/LoginPage'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginPageRoute: LoginPageRoute,
  WelcomePageRoute: WelcomePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
